# Generated by Django 4.2.30 on 2026-07-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_admin_chatmessage_is_deleted_by_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='admin',
        ),
    ]
