# Generated by Django 6.0.1 on 2026-01-31 17:16

import gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientimage',
            name='image_compressed',
            field=models.ImageField(blank=True, null=True, upload_to=gallery.models.client_folder_compressed_upload_path),
        ),
    ]
