# Generated by Django 6.0.1 on 2026-01-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_clientimage_image_compressed'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientimage',
            name='folio',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientimage',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
