# Generated by Django 6.0.1 on 2026-01-31 17:21

from django.db import migrations
import os


def populate_folios_and_titles(apps, schema_editor):
    """Generate folios and titles for existing images"""
    ClientImage = apps.get_model('gallery', 'ClientImage')

    for image in ClientImage.objects.all():
        if not image.folio:
            # Count images in the same folder
            image_count = ClientImage.objects.filter(
                folder=image.folder,
                id__lte=image.id
            ).count()

            # Generate folio
            image.folio = f"CLI-{image.folder.client.id}-FOL-{image.folder.id}-IMG-{image_count:03d}"

        if not image.title and image.image:
            # Extract filename without extension
            filename = os.path.basename(image.image.name)
            image.title = os.path.splitext(filename)[0]

        image.save()


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear folios and titles"""
    ClientImage = apps.get_model('gallery', 'ClientImage')
    ClientImage.objects.all().update(folio=None, title='')


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_clientimage_folio_clientimage_title'),
    ]

    operations = [
        migrations.RunPython(populate_folios_and_titles, reverse_populate),
    ]
