# Generated by Django 6.0.1 on 2026-01-31 17:26

from django.db import migrations


def update_folio_format(apps, schema_editor):
    """Update existing folios to new format: C{client_id}F{folder_id}-{count}"""
    ClientImage = apps.get_model('gallery', 'ClientImage')

    for image in ClientImage.objects.all():
        # Count images in the same folder up to this image's position
        image_count = ClientImage.objects.filter(
            folder=image.folder,
            id__lte=image.id
        ).count()

        # Generate new folio format: C5F12-001
        image.folio = f"C{image.folder.client.id}F{image.folder.id}-{image_count:03d}"
        image.save()


def reverse_update(apps, schema_editor):
    """Reverse to old format: CLI-{client_id}-FOL-{folder_id}-IMG-{count}"""
    ClientImage = apps.get_model('gallery', 'ClientImage')

    for image in ClientImage.objects.all():
        image_count = ClientImage.objects.filter(
            folder=image.folder,
            id__lte=image.id
        ).count()

        # Generate old folio format
        image.folio = f"CLI-{image.folder.client.id}-FOL-{image.folder.id}-IMG-{image_count:03d}"
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_populate_folios'),
    ]

    operations = [
        migrations.RunPython(update_folio_format, reverse_update),
    ]
