# Generated by Django 6.0.1 on 2026-07-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_update_folio_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfolder',
            name='is_system_folder',
            field=models.BooleanField(default=False, help_text='System folder (e.g. shared content) that cannot be deleted or renamed'),
        ),
    ]
