# Generated by Django 6.0.1 on 2026-01-21 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPERUSER', 'CONTENT_CREATOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_monthly_requests', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
    ]
