# Generated by Django 6.0.1 on 2026-01-23 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_monthlyrequest_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrequest',
            name='request_type',
            field=models.CharField(choices=[('MONTHLY_CONTENT', 'Monthly Content'), ('VIDEO_SHOOT', 'Video Shoot'), ('CONTENT_REQUEST', 'Content Request')], default='MONTHLY_CONTENT', max_length=50, verbose_name='Request Type'),
        ),
        migrations.AlterField(
            model_name='monthlyrequest',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('QA', 'QA'), ('IN_REVISION', 'In Revision'), ('DONE', 'Done')], default='TO_DO', max_length=20),
        ),
    ]
