# Generated by Django 6.0.1 on 2026-01-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_monthlyrequest_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrequest',
            name='ai_caption',
            field=models.TextField(blank=True, null=True, verbose_name='AI Caption'),
        ),
        migrations.AddField(
            model_name='monthlyrequest',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='Content Text'),
        ),
    ]
