# Generated by Django 6.0.1 on 2026-01-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_monthlyrequest_ai_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrequest',
            name='feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Feedback'),
        ),
    ]
