# Generated by Django 6.0.1 on 2026-01-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_requesthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='galeria/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
