# Generated by Django 6.0.1 on 2026-02-04 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_monthlyrequest_qa_assigned_to'),
        ('gallery', '0005_update_folio_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrequest',
            name='linked_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_requests', to='gallery.clientimage', verbose_name='Linked Gallery Image'),
        ),
    ]
