# Generated by Django 6.0.1 on 2026-02-04 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_monthlyrequest_linked_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrequest',
            name='available_from',
            field=models.DateField(blank=True, help_text='Date when this request becomes active/visible', null=True, verbose_name='Available From'),
        ),
    ]
