# Generated by Django 6.0.1 on 2026-06-23 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_letstalksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyrequest',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('QA', 'QA'), ('IN_REVISION', 'In Revision'), ('CLIENT_REVIEW', 'Client Review'), ('APPROVED', 'Approved'), ('DONE', 'Done')], default='TO_DO', max_length=20),
        ),
    ]
