# Generated by Django 6.0.1 on 2026-07-14 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_alter_monthlyrequest_status'),
        ('gallery', '0005_update_folio_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('CAROUSEL_IMAGE', 'Carousel Image'), ('STORY', 'Story')], default='IMAGE', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('file_url', models.URLField(blank=True, max_length=500)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_items', to='gallery.clientimage')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_items', to='contents.monthlyrequest')),
            ],
            options={
                'verbose_name': 'Content Item',
                'verbose_name_plural': 'Content Items',
                'ordering': ['order'],
            },
        ),
    ]
