# Generated by Django 6.0.1 on 2026-07-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_contentitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='file_url',
            field=models.TextField(blank=True),
        ),
    ]
