# Generated by Django 6.0.1 on 2026-07-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_alter_contentitem_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyrequest',
            name='client_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='Client Feedback'),
        ),
    ]
