# Generated by Django 4.2.30 on 2026-07-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_add_client_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='imagenproyecto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='letstalksubmission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monthlyrequest',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='requesthistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
