# Generated by Django 6.0.1 on 2026-07-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_socialaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='postproxy_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Postproxy ID'),
        ),
    ]
