# Generated by Django 6.0.1 on 2026-01-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPERUSER', 'Superuser'), ('QA', 'QA'), ('CLIENT', 'Client'), ('CONTENT_CREATOR', 'Content Creator'), ('EDITOR', 'Editor')], default='CONTENT_CREATOR', max_length=50, verbose_name='Role'),
        ),
    ]
