# Generated by Django 6.0.1 on 2026-01-23 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_name', models.CharField(blank=True, max_length=255)),
                ('primary_contact', models.CharField(blank=True, max_length=255)),
                ('role_title', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('practice_address', models.TextField(blank=True)),
                ('time_zone', models.CharField(blank=True, max_length=100)),
                ('medical_specialty', models.CharField(blank=True, max_length=255)),
                ('sub_specialty', models.CharField(blank=True, max_length=255)),
                ('practice_type', models.CharField(blank=True, max_length=100)),
                ('target_patient_type', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('brand_colors', models.TextField(blank=True, help_text='Comma separated or description')),
                ('brand_fonts', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('social_media_links', models.TextField(blank=True)),
                ('primary_brand_pillars', models.TextField(blank=True)),
                ('overall_voice', models.CharField(blank=True, max_length=255)),
                ('emojis', models.CharField(blank=True, max_length=100)),
                ('humor', models.CharField(blank=True, max_length=100)),
                ('formality_level', models.CharField(blank=True, max_length=100)),
                ('words_to_use', models.TextField(blank=True)),
                ('words_to_avoid', models.TextField(blank=True)),
                ('doctor_voice_preference', models.TextField(blank=True)),
                ('topics_to_emphasize', models.TextField(blank=True)),
                ('topics_to_avoid', models.TextField(blank=True)),
                ('medical_claims_limitations', models.TextField(blank=True)),
                ('hipaa_considerations', models.TextField(blank=True)),
                ('faces_allowed', models.CharField(blank=True, max_length=50)),
                ('testimonials_allowed', models.CharField(blank=True, max_length=50)),
                ('consent_required', models.CharField(blank=True, max_length=50)),
                ('primary_goal', models.TextField(blank=True)),
                ('secondary_goals', models.TextField(blank=True)),
                ('kpis_to_track', models.TextField(blank=True)),
                ('success_looks_like', models.TextField(blank=True)),
                ('communication_channel', models.CharField(blank=True, max_length=100)),
                ('feedback_style', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
