# Generated by Django 6.0.1 on 2026-01-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_permissions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Access Permissions'),
        ),
    ]
