# Generated by Django 6.0.1 on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_access_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='insights_metrics',
            field=models.JSONField(blank=True, default=dict, verbose_name='Insights Metrics'),
        ),
    ]
